# Generated by Django 6.0 on 2025-12-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userlist_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='movie_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
